# Generated by Django 3.0.6 on 2020-05-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeprojects', '0002_auto_20200515_1751'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectlanguage',
            constraint=models.UniqueConstraint(fields=('project', 'language'), name='unique_pairing'),
        ),
    ]
