# Generated by Django 3.0.6 on 2020-05-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('codeprojects', '0003_auto_20200516_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='education.Course'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='Description to be added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('TUT', 'Tutorial'), ('COU', 'Graded Coursework'), ('IND', 'Individual Project'), ('COM', 'Commission')], default='IND', max_length=3),
        ),
    ]
